macro(print_all_variables)
    get_cmake_property(_variableNames VARIABLES)
    foreach (_variableName ${_variableNames})
        message(STATUS "${_variableName}===>${${_variableName}}")
    endforeach ()
endmacro()


macro(print_variable var)
    message(STATUS "${var} ===> ${${var}}")
endmacro()

macro(custom_print_variables)
    message(STATUS "========================================")
    print_variable(PROJECT_NAME)
    print_variable(PROJECT_VERSION)
    print_variable(PROJECT_DESCRIPTION)
    print_variable(PROJECT_HOMEPAGE_URL)
    print_variable(PROJECT_SOURCE_DIR)
    print_variable(PROJECT_BINARY_DIR)
    print_variable(PROJECT_IS_TOP_LEVEL)
    message(STATUS "========================================")
    print_variable(CMAKE_SOURCE_DIR)
    print_variable(CMAKE_BINARY_DIR)
    print_variable(CMAKE_INSTALL_PREFIX)
    print_variable(CMAKE_CACHEFILE_DIR)
    message(STATUS "========================================")
    print_variable(CMAKE_CURRENT_LIST_DIR)
    print_variable(CMAKE_CURRENT_LIST_FILE)
    print_variable(CMAKE_CURRENT_SOURCE_DIR)
    print_variable(CMAKE_CURRENT_BINARY_DIR)
    message(STATUS "========================================")
    print_variable(CMAKE_PREFIX_PATH)
    print_variable(CMAKE_MODULE_PATH)
    print_variable(CMAKE_INCLUDE_PATH)
    print_variable(CMAKE_LIBRARY_PATH)
    print_variable(CMAKE_SYSTEM_PREFIX_PATH)
#    print_variable(EXECUTABLE_OUTPUT_PATH)
#    print_variable(LIBRARY_OUTPUT_PATH)
#    print_variable(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
#    print_variable(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
    message(STATUS "========================================")
    print_variable(CMAKE_BUILD_TYPE)
    print_variable(CMAKE_CONFIGURATION_TYPES)
    print_variable(CMAKE_GENERATOR)
    print_variable(CMAKE_GENERATOR_INSTANCE)
    print_variable(CMAKE_GENERATOR_PLATFORM)
    print_variable(CMAKE_GENERATOR_TOOLSET)
    print_variable(CMAKE_TOOLCHAIN_FILE)
    print_variable(CMAKE_MAKE_PROGRAM)
    print_variable(CMAKE_COMMAND)
    print_variable(CMAKE_CTEST_COMMAND)
    print_variable(CMAKE_CPACK_COMMAND)
    print_variable(CMAKE_VERSION)
    message(STATUS "========================================")
    print_variable(CMAKE_C_COMPILER)
    print_variable(CMAKE_C_COMPILER_LINKER)
    print_variable(C_STANDARD)
    print_variable(C_STANDARD_REQUIRED)
    print_variable(CMAKE_C_EXTENSIONS)
    print_variable(CMAKE_C_FLAGS)
    print_variable(CMAKE_C_FLAGS_DEBUG)
    print_variable(CMAKE_C_FLAGS_RELEASE)
    message(STATUS "========================================")
    print_variable(CMAKE_CXX_COMPILER)
    print_variable(CMAKE_CXX_COMPILER_LINKER)
    print_variable(CXX_STANDARD)
    print_variable(CXX_STANDARD_REQUIRED)
    print_variable(CXX_EXTENSIONS)
    print_variable(CMAKE_CXX_FLAGS)
    print_variable(CMAKE_CXX_FLAGS_DEBUG)
    print_variable(CMAKE_CXX_FLAGS_RELEASE)
    message(STATUS "========================================")
    print_variable(CMAKE_SYSTEM_NAME)
    print_variable(CMAKE_SYSTEM_VERSION)
    print_variable(CMAKE_SYSTEM_PROCESSOR)
    print_variable(CMAKE_HOST_SYSTEM_NAME)
    print_variable(CMAKE_HOST_SYSTEM_PROCESSOR)
    print_variable(WIN32)
    print_variable(UNIX)
    print_variable(APPLE)
    print_variable(LINUX)
endmacro()

# CMake 内置变量
# 指定编译工具链：-DCMAKE_TOOLCHAIN_FILE=toolchain.cmake
# 设置构建类型：-DCMAKE_BUILD_TYPE=Release
# 指定安装路径：-DCMAKE_INSTALL_PREFIX=/usr/local